import 'package:flutter/material.dart';

final Map<String, IconData> iconMap = {
  "home": Icons.home,
  "delete": Icons.delete,
  "food_bank": Icons.food_bank_rounded,
  "shopping_cart": Icons.shopping_cart,
  "alarm": Icons.alarm,
  "pets": Icons.pets,
  "work": Icons.work,
  "school": Icons.school,
  "flight": Icons.flight,
  "hotel": Icons.hotel,
  "mood_bad": Icons.mood_bad,
  "backup_table": Icons.backup_table,
  "fitness_center": Icons.fitness_center,
  "book": Icons.book,
  "event": Icons.event,
  "mood": Icons.mood,
  "music_note": Icons.music_note,
  "photo_camera": Icons.photo_camera,
  "place": Icons.place,
  "restaurant": Icons.restaurant,
  "favorite": Icons.favorite,
  "search": Icons.search,
  "sports_soccer": Icons.sports_soccer,
  "local_library": Icons.local_library,
  "local_cafe": Icons.local_cafe,
  "notifications": Icons.notifications,
  "mail": Icons.mail,
  "message": Icons.message,
  "directions_bike": Icons.directions_bike,
  "local_movies": Icons.local_movies,
  "computer": Icons.computer,
  "nature": Icons.nature,
  "language": Icons.language,
  "settings": Icons.settings,
  "dashboard": Icons.dashboard,
  "play_circle_filled": Icons.play_circle_filled,
  "stop": Icons.stop,
  "battery_full": Icons.battery_full,
  "wifi": Icons.wifi,
  "volume_up": Icons.volume_up,
  "volume_mute": Icons.volume_mute,
  "visibility": Icons.visibility,
  "visibility_off": Icons.visibility_off,
  "lock": Icons.lock,
  "lock_open": Icons.lock_open,
  "group": Icons.group,
  "account_circle": Icons.account_circle,
  "refresh": Icons.refresh,
  "edit": Icons.edit,
  "check_circle": Icons.check_circle,
  "highlight_off": Icons.highlight_off,
};

final List<String> emojiList = [
  "🍎",
  "🍌",
  "🍕",
  "🚗",
  "⌚",
  "📚",
  "🎁",
  "🍆",
  "🎮",
  "🎸",
  "📷",
  "🔨",
  "👓",
  "👟",
  "👜",
  "🌻",
  "🌈",
  "🍔",
  "🎉",
  "🏀",
  "🎤",
  "🖌️",
  "📺",
  "🛒",
  "⛳",
  "💻",
  "🏠",
  "🎬",
  "✈️",
  "🏖️",
  "🏋️",
  "🚵",
  "🎯",
  "🎲",
  "🧩",
  "🎹",
  "📖",
  "✏️",
  "🌂",
  "🍿",
  "🧸",
  "🎃",
  "🕹️",
  "🧹",
  "🧽",
  "🔧",
  "🧰",
  "🛏️",
  "🧳",
  "⛱️",
  "📽️",
  "🎨",
  "🛁",
  "💡",
  "🔭",
  "📒",
  "🔑",
  "📱",
  "🖥️",
  "🖱️",
  "📹",
  "💿",
  "🔔",
  "🎵",
  "📎",
  "🔖",
];
